openapi: 3.0.0
info:
  title: Plastic Dump Sites API
  description: API for finding plastic sites detected via machile learning. See [Global Plastics Watch](https://gpw.earthrise.media/)
  version: 0.0.1
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/tingold/Plastics/0.0.1
  - url: http://api.earthrise.com/v1/plastics/
    description: Production (notional)
  - url: http://api-dev.earthrise.com/v1/plastics/
    description: Developement (notional)
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

paths:
  /sites:
    get:
      tags:
        - All Sites
      summary: Returns a collection of sites.
      description: This endpoint can be used to find specific sites using a bounding box and times
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            default: 100
          description: The maximum number of sites to return
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
            minimum: 0
          description: The offset from the start of the collection (sorting is internal currently)
        - in: query
          name: bbox
          description: 'bounding coordinates in decimal degrees in the following order:  minlon,maxlon,minlat,maxlat'
          style: form
          explode: false
          schema:
            type: array
            items:
              type: number
              minimum: -180
              maximum: 180
            default: -180.00,180.00,-90.00,90.00
          example: '-180.00,180.00,-90.00,90.00'
      responses:
        '200':
          description: 'A geojson formatted feature collection containing centroids of platic sites, metadata about the site and a URL to retrieve more detailed information'
          content:
            application/json:
              schema:
                $ref: 'https://geojson.org/schema/FeatureCollection.json'
              example:
                type: FeatureCollection
                features:
                  - type: Feature
                    properties:
                      id: site_1
                      first_detected: '2019-09-07T15:50+00Z'
                      last_detected: '2021-06-14T12:50+00Z'
                      ref: 'http://api.earthrise.com/v1/platics/sites/site_1'
                    geometry:
                      type: Point
                      coordinates:
                        - -7.159857
                        - 111.559408
                  - type: Feature
                    properties:
                      id: site_2
                      first_detected: '2019-10-07T15:50+00Z'
                      last_detected: '2021-06-14T12:50+00Z'
                      ref: 'http://api.earthrise.com/v1/platics/sites/site_2'
                    geometry:
                      type: Point
                      coordinates:
                        - -7.5767857
                        - 112.559408
        '400':
          description: Bad request, parameters are likely invalid
          content:
            application/problem+json:
              schema:
                $ref: 'https://gist.githubusercontent.com/tingold/8adc09ee326fd67bbbcaaa002b950618/raw/4a5753727d47a124fe9433585a90998bd3eccab3/gistfile1.txt#/definitions/validation'
        '401':
          description: Not allowed
          content:
            application/problem+json:
              schema:
                $ref: 'https://gist.githubusercontent.com/tingold/8adc09ee326fd67bbbcaaa002b950618/raw/4a5753727d47a124fe9433585a90998bd3eccab3/gistfile1.txt#/definitions/validation'

    post:
      tags:
        - All Sites
        - Specific Sites
      summary: Creates 1 or more sites
      description: Creates 1 or more sites by ingesting a feature collection containing 1 or more features with Point geometries
      security:
        - BasicAuth: []
      requestBody:
        description: A contour encoded as a geojson feature collectoion. Only a point geometry is allowed
        required: true
        content:
          application/json:
            schema:
              $ref: 'https://geojson.org/schema/FeatureCollection.json'
      responses:
        '201':
          description: The service will echo out sites that have been added to the database and will also include an ID as a property. This ID can be used to identify the site for future requests
        '401':
          description: Not Authorized
          content:
            application/problem+json:
              schema:
                $ref: 'https://gist.githubusercontent.com/tingold/8adc09ee326fd67bbbcaaa002b950618/raw/4a5753727d47a124fe9433585a90998bd3eccab3/gistfile1.txt#/definitions/validation'


    delete:
      tags:
        - All Sites
      summary: Deletes all of the sites
      description: deletes all of the sites in the database including associated countours
      security:
        - BasicAuth: []
      responses:
        '204':
          description: Sites were deleted, no response body
        '401':
          description: Auth failed, sites were not deleted

  /sites/{site_id}:
    delete:
      tags:
        - Specific Sites
      summary: Deletes the specified site
      description: Deletes the specified site including associated countours
      security:
        - BasicAuth: []
      parameters:
        - in: path
          name: site_id
          required: true
          schema:
            type: string
          description: The site id
      responses:
        '204':
          description: Site was deleted, no response body
        '401':
          description: Auth failed, site was not deleted

    get:
      tags:
        - Specific Sites
      summary: Returns details for a given site.
      description: Returns details for a given site.
      parameters:
        - in: path
          name: site_id
          required: true
          schema:
            type: string
          description: The site id
      responses:
        '200':
          description: 'A geojson formatted featureCollection containing the history of detections (contours) for a given site.'
          content:
            application/json:
              schema:
                $ref: 'https://geojson.org/schema/FeatureCollection.json'
              example:
                type: FeatureCollection
                features:
                  - type: Feature
                    properties:
                      id: site_1
                      date: 2019-09-07T15:50+00Z
                    geometry:
                      type: MultiPolygon
                      coordinates:
                        -
                          -
                            -
                              - 0
                              - 0
                            -
                              - 0
                              - 1
                            -
                              - 1
                              - 1
                            -
                              - 1
                              - 0
                            -
                              - 0
                              - 0
                  - type: Feature
                    properties:
                      id: site_1
                      date: 2021-06-14T12:50+00Z
                    geometry:
                      type: MultiPolygon
                      coordinates:
                        -
                          -
                            -
                              - 0
                              - 0
                            -
                              - 0
                              - 1
                            -
                              - 1
                              - 1
                            -
                              - 1
                              - 0
                            -
                              - 0
                              - 0
        '400':
          description: Bad request, parameters are likely invalid
          content:
            application/problem+json:
              schema:
                $ref: 'https://gist.githubusercontent.com/tingold/8adc09ee326fd67bbbcaaa002b950618/raw/4a5753727d47a124fe9433585a90998bd3eccab3/gistfile1.txt#/definitions/validation'
    put:
      tags:
        - Specific Sites
      summary: Updates the specified site
      description: 'Updates the specified site with the provided geojson *TODO: need to figure out update semantics*'
      security:
        - BasicAuth: []
      parameters:
        - in: path
          name: site_id
          required: true
          schema:
            type: string
          description: The site id
      requestBody:
        description: A contour encoded as a geojson feature collectoion. Only a point geometry is allowed
        required: true
        content:
          application/json:
            schema:
              $ref: 'https://geojson.org/schema/Feature.json'
      responses:
        '204':
          description: Successful updates will not return any content
        '401':
          description: Not Authorized
          content:
            application/problem+json:
              schema:
                $ref: 'https://gist.githubusercontent.com/tingold/8adc09ee326fd67bbbcaaa002b950618/raw/4a5753727d47a124fe9433585a90998bd3eccab3/gistfile1.txt#/definitions/validation'



  /sites/{site_id}/countours:
    get:
      tags:
        - All Contours
      summary: Returns a collection of countours .
      description: This endpoint allows query using location and time to find contours
      parameters:
        - in: path
          name: site_id
          required: true
          schema:
            type: string
          description: The site id
        - in: query
          name: limit
          schema:
            type: integer
            default: 100
          description: The maximum number of contours to return
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
            minimum: 0
          description: The offset from the start of the collection (sorting is internal currently)
      responses:
        '200':
          description: 'A geojson formatted feature collection containing multipolygons of contours, metadata about each contour and a URL ref to the site the contour belongs to'
          content:
            application/json:
              schema:
                $ref: 'https://geojson.org/schema/FeatureCollection.json'
        '400':
          description: error
          content:
            application/problem+json:
              schema:
                $ref: 'https://gist.githubusercontent.com/tingold/8adc09ee326fd67bbbcaaa002b950618/raw/4a5753727d47a124fe9433585a90998bd3eccab3/gistfile1.txt#/definitions/validation'
    post:
      tags:
        - All Contours
      summary: Adds a new contour
      description: Adds a new contour to the associated site
      security:
        - BasicAuth: []
      parameters:
        - in: path
          name: site_id
          required: true
          schema:
            type: string
          description: The site id
      requestBody:
        description: A contour encoded as a geojson feature. Only a multipolygon geometry is allowed
        required: true
        content:
          application/json:
            schema:
              $ref: 'https://geojson.org/schema/Feature.json'
      responses:
        '201':
          description: 'No content'
        '401':
          description: Not authorized
          content:
            application/problem+json:
              schema:
                $ref: 'https://gist.githubusercontent.com/tingold/8adc09ee326fd67bbbcaaa002b950618/raw/4a5753727d47a124fe9433585a90998bd3eccab3/gistfile1.txt#/definitions/validation'
    delete:
      tags:
        - All Contours
      summary: Deletes all contours
      description: Updates a countour by including geojson with an ID  as a property. If an ID is not provided this request will fail (as there is no countour ID to update). Adding new countours should be performed via POST
      security:
        - BasicAuth: []
      parameters:
        - in: path
          name: site_id
          required: true
          schema:
            type: string
          description: The site id
      responses:
        '204':
          description: Successful deletion will not return any content
        '401':
          description: Not authorized
          content:
            application/problem+json:
              schema:
                $ref: 'https://gist.githubusercontent.com/tingold/8adc09ee326fd67bbbcaaa002b950618/raw/4a5753727d47a124fe9433585a90998bd3eccab3/gistfile1.txt#/definitions/validation'

  /sites/{site_id}/countours/{contour_id}:
    put:
      tags:
        - Specific Contours
      summary: Updates a contour
      description: Updates a countour by including geojson with an ID  as a property. If an ID is not provided this request will fail (as there is no countour ID to update). Adding new countours should be performed via POST
      security:
        - BasicAuth: []
      parameters:
        - in: path
          name: site_id
          required: true
          schema:
            type: string
          description: The site id
        - in: path
          name: contour_id
          required: true
          schema:
            type: string
          description: The contour id
      requestBody:
        description: A contour encoded as a geojson feature. Only a multipolygon geometry is allowed
        required: true
        content:
          application/json:
            schema:
              $ref: 'https://geojson.org/schema/Feature.json'
      responses:
        '202':
          description: 'A geojson formatted feature containing multipolygons of the just submitted contour -- along with an ID in the properties'
        '401':
          description: Not authorized
          content:
            application/problem+json:
              schema:
                $ref: 'https://gist.githubusercontent.com/tingold/8adc09ee326fd67bbbcaaa002b950618/raw/4a5753727d47a124fe9433585a90998bd3eccab3/gistfile1.txt#/definitions/validation'
    delete:
      tags:
        - Specific Contours
      summary: Deletes a specific contours
      description: Updates a countour by including geojson with an ID  as a property. If an ID is not provided this request will fail (as there is no countour ID to update). Adding new countours should be performed via POST
      security:
        - BasicAuth: []
      parameters:
        - in: path
          name: site_id
          required: true
          schema:
            type: string
          description: The site id
        - in: path
          name: contour_id
          required: true
          schema:
            type: string
          description: The contour id
      responses:
        '200':
          description: 'No content sent when a contour is successfully deleted'
        '401':
          description: Not authorized
          content:
            application/problem+json:
              schema:
                $ref: 'https://gist.githubusercontent.com/tingold/8adc09ee326fd67bbbcaaa002b950618/raw/4a5753727d47a124fe9433585a90998bd3eccab3/gistfile1.txt#/definitions/validation'