name: Go
on:
  workflow_dispatch:
    branches: [ main, branches ]
  push:
    branches: [ main , branches ]
    paths: 
      - api/** 
  pull_request:
    branches: [ main ]

  
jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Vet
        working-directory: ./api
        run: go vet -v ./...
        continue-on-error: true
        
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Build
        run: go build
        working-directory: ./api  
  Test:
    name: Test
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: mdillon/postgis
        env:
          POSTGRES_DB: plastic
          POSTGRES_USER: postgis 
          POSTGRES_PASSWORD: password
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Test
        working-directory: ./api
        run:  go test .
        env:
          PGHOST: localhost
          PGPORT: 5432

        
