name: Go

on: workflow_dispatch


jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        working-directory: ./api
      - name: Vet
        run: go vet -v ./...
      - name: Build
        run: go build -v ./...
        working-directory: ./api
      - name: Test
        working-directory: ./api
        run: go test -v ./...
